- hosts: localhost
  become: true
  pre_tasks:
  - name: Update Cache
    apt:
      update_cache: yes
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
    - include: ansible_tasks/core-setup.yml
    - include: ansible_tasks/git-setup.yml
    - include: ansible_tasks/zsh-setup.yml
    - include: ansible_tasks/node-setup.yml
    - include: ansible_tasks/npm-packages.yml
    - include: ansible_tasks/nvim-setup.yml
    - include: ansible_tasks/productivity-tools.yml
    - include: ansible_tasks/git-setup.yml
    - include: ansible_tasks/gui-tools.yml
    - include: ansible_tasks/php-setup.yml
