- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: yes

  tasks:
    - include: ansible_tasks/zsh-setup.yml
    - include: ansible_tasks/node-setup.yml
