- hosts: localhost
  become: true
  tasks:
  - name: Install zsh
    apt: name=zsh
  - name: Change shell
    shell: chsh -s `which zsh`

  - name: Install Oh My Zsh # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/ohmyzsh/ohmyzsh.git
      dest: ~/.oh-my-zsh
      depth: 1

  - name: Install zsh-autosuggestions plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      depth: 1
  
  - name: Install zsh-completions plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-completions
      dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
      depth: 1
  
  - name: Install zsh-syntax-highlighting plugin # noqa: latest
    ansible.builtin.git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      depth: 1