- hosts: localhost
  become: false
  pre_tasks:
  - name: Update Cache
    apt:
      update_cache: true

  tasks:
    - include_tasks: ansible_tasks/core-setup.yml
    - include_tasks: ansible_tasks/git-setup.yml
    - include_tasks: ansible_tasks/zsh-setup.yml
    - include_tasks: ansible_tasks/node-setup.yml
    - include_tasks: ansible_tasks/npm-packages.yml
    - include_tasks: ansible_tasks/nvim-setup.yml
    - include_tasks: ansible_tasks/productivity-tools.yml
    - include_tasks: ansible_tasks/git-setup.yml
    - include_tasks: ansible_tasks/my-repos.yml
    - include_tasks: ansible_tasks/gui-tools.yml
    - include_tasks: ansible_tasks/php-setup.yml
