- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
# install neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim

- name: Build neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
  tags:
    - install
    - neovim

- name: Install neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim
# TODO: do the installing of nvchad
- name: Install NvChad
  ansible.builtin.git:
    repo: "https://github.com/NvChad/NvChad"
    dest: "{{ lookup('env', 'HOME') }}/.config/nvim"
  tags:
    - install
    - neovim
# link the nvim/custom to neovim - this requires this .dofiles repo to be presen in the $HOME
- name: Link custom nvim setup to NvChad
  shell: "ln -s $HOME/.dotfiles/nvim/lua/custom $HOME/.config/nvim/lua/custom"
  tags:
    - install
    - neovim

# Install NerdFont Jebrains Mono
- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Hack exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/JetBrainsMono*"
  register: hack_exists
  ignore_errors: yes

- name: Download Hack
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes
