# Productivity tools (apt packages require sudo)

- name: Install productivity packages
  become: true
  apt:
    name:
      - tmux
      - xclip
      - tldr
      - ripgrep
      - bat
      - sqlite3
      - fzf
      - gpg
      - zoxide
      - eza
    state: present
  tags: [install, productivity]
