- name: Install zsh
  apt: name=zsh
  tags: &tags_for_zsh_tasks ["install", "productivity", "zsh"]

- name: Change shell
  become: true
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: ensure fonts directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.fonts"
    state: directory

- name: Hack exists
  shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
  register: hack_exists
  ignore_errors: yes

- name: Download Hack
  when: hack_exists is failed
  ansible.builtin.unarchive:
    src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
    dest: "{{ lookup('env', 'HOME') }}/.fonts/"
    remote_src: yes

- name: Install Oh My Zsh # noqa: latest
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
  tags: *tags_for_zsh_tasks

- name: Install zsh-completions plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-completions
  tags: *tags_for_zsh_tasks

- name: Install zsh-syntax-highlighting plugin # noqa: latest
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
  tags: *tags_for_zsh_tasks

# Add plugins in to the .zshrc file (Junkie - probally should have a .zshrc in this repo)
- name: Add plugins name to the .zshrc file
  shell: sed -i 's/(git/(git zsh-autosuggestions zsh-syntax-highlighting/' ~/.zshrc
  tags: *tags_for_zsh_tasks
