#!/usr/bin/env bash
session=$(find ~ ~/Code -not -path "*/\.*" -mindepth 1 -maxdepth 2 -type d | fzf)

session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then
    tmux new-session -s "$session_name" -c "$session" -d
fi

if [ -z "$TMUX" ]; then
    tmux attach-session -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi

# Put this script into your .zshrc also put in nvim and put it in a key remap 
# Put the script into path
# bindkey -s ^f "tmux-sessionizer\n"
# test
